exports.imageActionType = Object.freeze({
  SET: 0,
  ADD: 1,
  REMOVE_SELECTED: 2,
  CHECK_CHANGE: 3,
  CHECK_CHANGE_ALL: 4,
  CHANGE_STATUS: 5,
})

exports.imageStatus = Object.freeze({
  COMPRESSING: 'COMPRESSING',
  COMPRESSED: 'COMPRESSED',
  FAILED: 'FAILED',
})

exports.APP_NAME = 'Image Panda'
exports.READY_TO_COMPRESS = 'READY_TO_COMPRESS'
exports.COMPRESSION_START = 'COMPRESSION_START'
exports.COMPRESSION_STATUS = 'COMPRESSION_STATUS'
exports.COMPRESSION_COUNT = 'COMPRESSION_COUNT'
exports.GET_IMAGES_FROM_USER = 'GET_IMAGES_FROM_USER'
exports.GET_DIRECTORY_FROM_USER = 'GET_DIRECTORY_FROM_USER'
